### PR TITLE
feat: revamp homepage & add sample articles

### PR DESCRIPTION
**Pull request by CIPHERTron**
# [PR] feat: revamp homepage & add sample articles

## Description

Revamped the homepage, added a new slack invite & removed the expired one. Added sample articles about Code Is Science, its manifesto & Devesh's GSoC'22 blog

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality).
- [x] This change requires a documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by CIPHERTron** [comment]
My bad. Didn’t see the workflows are failing. Will push a fix for this 💪🏼

**Review by ikayz — COMMENTED** [review]
This is for the community website right?

**Comment by CIPHERTron** [comment]
> This is for the community website right?

Yepp

**Comment by CIPHERTron** [comment]
Tests are passing. Thus, merging.

**Pull request merged**
